// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using galaxypremiere.Persistence.Context;

#nullable disable

namespace galaxypremiere.Persistence.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20231116095043_ModifyLanguagesConfiguration35")]
    partial class ModifyLanguagesConfiguration35
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("galaxypremiere.Domain.Common.Countries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("IP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 0,
                            IsActive = true,
                            Name = "Not Specified"
                        },
                        new
                        {
                            Id = 2,
                            Code = 93,
                            IsActive = true,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 3,
                            Code = 358,
                            IsActive = true,
                            Name = "Åland Islands"
                        },
                        new
                        {
                            Id = 4,
                            Code = 355,
                            IsActive = true,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 5,
                            Code = 213,
                            IsActive = true,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 6,
                            Code = 1,
                            IsActive = true,
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = 7,
                            Code = 376,
                            IsActive = true,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 8,
                            Code = 244,
                            IsActive = true,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 9,
                            Code = 1,
                            IsActive = true,
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 10,
                            Code = 1,
                            IsActive = true,
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 11,
                            Code = 54,
                            IsActive = true,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 12,
                            Code = 374,
                            IsActive = true,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 13,
                            Code = 297,
                            IsActive = true,
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 14,
                            Code = 61,
                            IsActive = true,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 15,
                            Code = 43,
                            IsActive = true,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 16,
                            Code = 994,
                            IsActive = true,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 17,
                            Code = 1,
                            IsActive = true,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 18,
                            Code = 973,
                            IsActive = true,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 19,
                            Code = 880,
                            IsActive = true,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 20,
                            Code = 1,
                            IsActive = true,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 21,
                            Code = 375,
                            IsActive = true,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 22,
                            Code = 32,
                            IsActive = true,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 23,
                            Code = 501,
                            IsActive = true,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 24,
                            Code = 229,
                            IsActive = true,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 25,
                            Code = 1,
                            IsActive = true,
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 26,
                            Code = 975,
                            IsActive = true,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 27,
                            Code = 591,
                            IsActive = true,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 28,
                            Code = 599,
                            IsActive = true,
                            Name = "Bonaire, Sint Eustatius and Saba"
                        },
                        new
                        {
                            Id = 29,
                            Code = 387,
                            IsActive = true,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 30,
                            Code = 267,
                            IsActive = true,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 31,
                            Code = 55,
                            IsActive = true,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 32,
                            Code = 246,
                            IsActive = true,
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = 33,
                            Code = 1,
                            IsActive = true,
                            Name = "British Virgin Islands"
                        },
                        new
                        {
                            Id = 34,
                            Code = 673,
                            IsActive = true,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 35,
                            Code = 359,
                            IsActive = true,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 36,
                            Code = 226,
                            IsActive = true,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 37,
                            Code = 257,
                            IsActive = true,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 38,
                            Code = 238,
                            IsActive = true,
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 39,
                            Code = 855,
                            IsActive = true,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 40,
                            Code = 237,
                            IsActive = true,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 41,
                            Code = 1,
                            IsActive = true,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 42,
                            Code = 0,
                            IsActive = true,
                            Name = "Caribbean"
                        },
                        new
                        {
                            Id = 43,
                            Code = 1,
                            IsActive = true,
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = 44,
                            Code = 236,
                            IsActive = true,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 45,
                            Code = 235,
                            IsActive = true,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 46,
                            Code = 56,
                            IsActive = true,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 47,
                            Code = 86,
                            IsActive = true,
                            Name = "China"
                        },
                        new
                        {
                            Id = 48,
                            Code = 61,
                            IsActive = true,
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Id = 49,
                            Code = 61,
                            IsActive = true,
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = 50,
                            Code = 57,
                            IsActive = true,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 51,
                            Code = 269,
                            IsActive = true,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 52,
                            Code = 242,
                            IsActive = true,
                            Name = "Congo"
                        },
                        new
                        {
                            Id = 53,
                            Code = 243,
                            IsActive = true,
                            Name = "Congo (DRC)"
                        },
                        new
                        {
                            Id = 54,
                            Code = 682,
                            IsActive = true,
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = 55,
                            Code = 506,
                            IsActive = true,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 56,
                            Code = 225,
                            IsActive = true,
                            Name = "Côte d’Ivoire"
                        },
                        new
                        {
                            Id = 57,
                            Code = 385,
                            IsActive = true,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 58,
                            Code = 53,
                            IsActive = true,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 59,
                            Code = 599,
                            IsActive = true,
                            Name = "Curaçao"
                        },
                        new
                        {
                            Id = 60,
                            Code = 357,
                            IsActive = true,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 61,
                            Code = 420,
                            IsActive = true,
                            Name = "Czechia"
                        },
                        new
                        {
                            Id = 62,
                            Code = 45,
                            IsActive = true,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 63,
                            Code = 253,
                            IsActive = true,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 64,
                            Code = 1,
                            IsActive = true,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 65,
                            Code = 1,
                            IsActive = true,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 66,
                            Code = 593,
                            IsActive = true,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 67,
                            Code = 20,
                            IsActive = true,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 68,
                            Code = 503,
                            IsActive = true,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 69,
                            Code = 240,
                            IsActive = true,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 70,
                            Code = 291,
                            IsActive = true,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 71,
                            Code = 372,
                            IsActive = true,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 72,
                            Code = 251,
                            IsActive = true,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 73,
                            Code = 0,
                            IsActive = true,
                            Name = "Europe"
                        },
                        new
                        {
                            Id = 74,
                            Code = 500,
                            IsActive = true,
                            Name = "Falkland Islands"
                        },
                        new
                        {
                            Id = 75,
                            Code = 298,
                            IsActive = true,
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 76,
                            Code = 679,
                            IsActive = true,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 77,
                            Code = 358,
                            IsActive = true,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 78,
                            Code = 33,
                            IsActive = true,
                            Name = "France"
                        },
                        new
                        {
                            Id = 79,
                            Code = 594,
                            IsActive = true,
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = 80,
                            Code = 689,
                            IsActive = true,
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = 81,
                            Code = 241,
                            IsActive = true,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 82,
                            Code = 220,
                            IsActive = true,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 83,
                            Code = 995,
                            IsActive = true,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 84,
                            Code = 49,
                            IsActive = true,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 85,
                            Code = 233,
                            IsActive = true,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 86,
                            Code = 350,
                            IsActive = true,
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 87,
                            Code = 30,
                            IsActive = true,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 88,
                            Code = 299,
                            IsActive = true,
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 89,
                            Code = 1,
                            IsActive = true,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 90,
                            Code = 590,
                            IsActive = true,
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = 91,
                            Code = 1,
                            IsActive = true,
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 92,
                            Code = 502,
                            IsActive = true,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 93,
                            Code = 44,
                            IsActive = true,
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = 94,
                            Code = 224,
                            IsActive = true,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 95,
                            Code = 245,
                            IsActive = true,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 96,
                            Code = 592,
                            IsActive = true,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 97,
                            Code = 509,
                            IsActive = true,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 98,
                            Code = 504,
                            IsActive = true,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 99,
                            Code = 852,
                            IsActive = true,
                            Name = "Hong Kong SAR"
                        },
                        new
                        {
                            Id = 100,
                            Code = 36,
                            IsActive = true,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 101,
                            Code = 354,
                            IsActive = true,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 102,
                            Code = 91,
                            IsActive = true,
                            Name = "India"
                        },
                        new
                        {
                            Id = 103,
                            Code = 62,
                            IsActive = true,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 104,
                            Code = 98,
                            IsActive = true,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 105,
                            Code = 964,
                            IsActive = true,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 106,
                            Code = 353,
                            IsActive = true,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 107,
                            Code = 44,
                            IsActive = true,
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = 108,
                            Code = 972,
                            IsActive = true,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 109,
                            Code = 39,
                            IsActive = true,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 110,
                            Code = 1,
                            IsActive = true,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 111,
                            Code = 81,
                            IsActive = true,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 112,
                            Code = 44,
                            IsActive = true,
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = 113,
                            Code = 962,
                            IsActive = true,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 114,
                            Code = 7,
                            IsActive = true,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 115,
                            Code = 254,
                            IsActive = true,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 116,
                            Code = 686,
                            IsActive = true,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 117,
                            Code = 82,
                            IsActive = true,
                            Name = "Korea"
                        },
                        new
                        {
                            Id = 118,
                            Code = 383,
                            IsActive = true,
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = 119,
                            Code = 965,
                            IsActive = true,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 120,
                            Code = 996,
                            IsActive = true,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 121,
                            Code = 856,
                            IsActive = true,
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 122,
                            Code = 0,
                            IsActive = true,
                            Name = "Latin America"
                        },
                        new
                        {
                            Id = 123,
                            Code = 371,
                            IsActive = true,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 124,
                            Code = 961,
                            IsActive = true,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 125,
                            Code = 266,
                            IsActive = true,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 126,
                            Code = 231,
                            IsActive = true,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 127,
                            Code = 218,
                            IsActive = true,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 128,
                            Code = 423,
                            IsActive = true,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 129,
                            Code = 370,
                            IsActive = true,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 130,
                            Code = 352,
                            IsActive = true,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 131,
                            Code = 853,
                            IsActive = true,
                            Name = "Macao SAR"
                        },
                        new
                        {
                            Id = 132,
                            Code = 389,
                            IsActive = true,
                            Name = "Macedonia, FYRO"
                        },
                        new
                        {
                            Id = 133,
                            Code = 261,
                            IsActive = true,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 134,
                            Code = 265,
                            IsActive = true,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 135,
                            Code = 60,
                            IsActive = true,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 136,
                            Code = 960,
                            IsActive = true,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 137,
                            Code = 223,
                            IsActive = true,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 138,
                            Code = 356,
                            IsActive = true,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 139,
                            Code = 692,
                            IsActive = true,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 140,
                            Code = 596,
                            IsActive = true,
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = 141,
                            Code = 222,
                            IsActive = true,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 142,
                            Code = 230,
                            IsActive = true,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 143,
                            Code = 262,
                            IsActive = true,
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 144,
                            Code = 52,
                            IsActive = true,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 145,
                            Code = 691,
                            IsActive = true,
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 146,
                            Code = 373,
                            IsActive = true,
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 147,
                            Code = 377,
                            IsActive = true,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 148,
                            Code = 976,
                            IsActive = true,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 149,
                            Code = 382,
                            IsActive = true,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 150,
                            Code = 1,
                            IsActive = true,
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 151,
                            Code = 212,
                            IsActive = true,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 152,
                            Code = 258,
                            IsActive = true,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 153,
                            Code = 95,
                            IsActive = true,
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 154,
                            Code = 264,
                            IsActive = true,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 155,
                            Code = 674,
                            IsActive = true,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 156,
                            Code = 977,
                            IsActive = true,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 157,
                            Code = 31,
                            IsActive = true,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 158,
                            Code = 687,
                            IsActive = true,
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = 159,
                            Code = 64,
                            IsActive = true,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 160,
                            Code = 505,
                            IsActive = true,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 161,
                            Code = 227,
                            IsActive = true,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 162,
                            Code = 234,
                            IsActive = true,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 163,
                            Code = 683,
                            IsActive = true,
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 164,
                            Code = 672,
                            IsActive = true,
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = 165,
                            Code = 850,
                            IsActive = true,
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = 166,
                            Code = 1,
                            IsActive = true,
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = 167,
                            Code = 47,
                            IsActive = true,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 168,
                            Code = 968,
                            IsActive = true,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 169,
                            Code = 92,
                            IsActive = true,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 170,
                            Code = 680,
                            IsActive = true,
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 171,
                            Code = 970,
                            IsActive = true,
                            Name = "Palestinian Authority"
                        },
                        new
                        {
                            Id = 172,
                            Code = 507,
                            IsActive = true,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 173,
                            Code = 675,
                            IsActive = true,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 174,
                            Code = 595,
                            IsActive = true,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 175,
                            Code = 51,
                            IsActive = true,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 176,
                            Code = 63,
                            IsActive = true,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 177,
                            Code = 0,
                            IsActive = true,
                            Name = "Pitcairn Islands"
                        },
                        new
                        {
                            Id = 178,
                            Code = 48,
                            IsActive = true,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 179,
                            Code = 351,
                            IsActive = true,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 180,
                            Code = 1,
                            IsActive = true,
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 181,
                            Code = 974,
                            IsActive = true,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 182,
                            Code = 262,
                            IsActive = true,
                            Name = "Réunion"
                        },
                        new
                        {
                            Id = 183,
                            Code = 40,
                            IsActive = true,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 184,
                            Code = 7,
                            IsActive = true,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 185,
                            Code = 250,
                            IsActive = true,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 186,
                            Code = 590,
                            IsActive = true,
                            Name = "Saint Barthélemy"
                        },
                        new
                        {
                            Id = 187,
                            Code = 1,
                            IsActive = true,
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 188,
                            Code = 1,
                            IsActive = true,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 189,
                            Code = 590,
                            IsActive = true,
                            Name = "Saint Martin"
                        },
                        new
                        {
                            Id = 190,
                            Code = 508,
                            IsActive = true,
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = 191,
                            Code = 1,
                            IsActive = true,
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 192,
                            Code = 685,
                            IsActive = true,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 193,
                            Code = 378,
                            IsActive = true,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 194,
                            Code = 239,
                            IsActive = true,
                            Name = "São Tomé and Príncipe"
                        },
                        new
                        {
                            Id = 195,
                            Code = 966,
                            IsActive = true,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 196,
                            Code = 221,
                            IsActive = true,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 197,
                            Code = 381,
                            IsActive = true,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 198,
                            Code = 248,
                            IsActive = true,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 199,
                            Code = 232,
                            IsActive = true,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 200,
                            Code = 65,
                            IsActive = true,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 201,
                            Code = 1,
                            IsActive = true,
                            Name = "Sint Maarten"
                        },
                        new
                        {
                            Id = 202,
                            Code = 421,
                            IsActive = true,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 203,
                            Code = 386,
                            IsActive = true,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 204,
                            Code = 677,
                            IsActive = true,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 205,
                            Code = 252,
                            IsActive = true,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 206,
                            Code = 27,
                            IsActive = true,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 207,
                            Code = 211,
                            IsActive = true,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 208,
                            Code = 34,
                            IsActive = true,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 209,
                            Code = 94,
                            IsActive = true,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 210,
                            Code = 290,
                            IsActive = true,
                            Name = "St Helena, Ascension, Tristan da Cunha"
                        },
                        new
                        {
                            Id = 211,
                            Code = 249,
                            IsActive = true,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 212,
                            Code = 597,
                            IsActive = true,
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 213,
                            Code = 47,
                            IsActive = true,
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = 214,
                            Code = 268,
                            IsActive = true,
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = 215,
                            Code = 46,
                            IsActive = true,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 216,
                            Code = 41,
                            IsActive = true,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 217,
                            Code = 963,
                            IsActive = true,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 218,
                            Code = 886,
                            IsActive = true,
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 219,
                            Code = 992,
                            IsActive = true,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 220,
                            Code = 255,
                            IsActive = true,
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 221,
                            Code = 66,
                            IsActive = true,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 222,
                            Code = 670,
                            IsActive = true,
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 223,
                            Code = 228,
                            IsActive = true,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 224,
                            Code = 690,
                            IsActive = true,
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = 225,
                            Code = 676,
                            IsActive = true,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 226,
                            Code = 1,
                            IsActive = true,
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 227,
                            Code = 216,
                            IsActive = true,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 228,
                            Code = 90,
                            IsActive = true,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 229,
                            Code = 993,
                            IsActive = true,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 230,
                            Code = 1,
                            IsActive = true,
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = 231,
                            Code = 688,
                            IsActive = true,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 232,
                            Code = 0,
                            IsActive = true,
                            Name = "U.S. Outlying Islands"
                        },
                        new
                        {
                            Id = 233,
                            Code = 1,
                            IsActive = true,
                            Name = "U.S. Virgin Islands"
                        },
                        new
                        {
                            Id = 234,
                            Code = 256,
                            IsActive = true,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 235,
                            Code = 380,
                            IsActive = true,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 236,
                            Code = 971,
                            IsActive = true,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 237,
                            Code = 44,
                            IsActive = true,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 238,
                            Code = 1,
                            IsActive = true,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 239,
                            Code = 598,
                            IsActive = true,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 240,
                            Code = 998,
                            IsActive = true,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 241,
                            Code = 678,
                            IsActive = true,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 242,
                            Code = 39,
                            IsActive = true,
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = 243,
                            Code = 58,
                            IsActive = true,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 244,
                            Code = 84,
                            IsActive = true,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 245,
                            Code = 681,
                            IsActive = true,
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = 246,
                            Code = 0,
                            IsActive = true,
                            Name = "World"
                        },
                        new
                        {
                            Id = 247,
                            Code = 967,
                            IsActive = true,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 248,
                            Code = 260,
                            IsActive = true,
                            Name = "Zambia"
                        });
                });

            modelBuilder.Entity("galaxypremiere.Domain.Common.Languages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LanguageCountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameNative")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameEnglish = "Not Specified",
                            NameNative = "Not Specified"
                        },
                        new
                        {
                            Id = 2,
                            LanguageCountryCode = "aa-DJ",
                            NameEnglish = "Afar (Djibouti)",
                            NameNative = "Afar (Djibouti)"
                        },
                        new
                        {
                            Id = 3,
                            LanguageCountryCode = "aa-ER",
                            NameEnglish = "Afar (Eritrea)",
                            NameNative = "Afar (Eritrea)"
                        },
                        new
                        {
                            Id = 4,
                            LanguageCountryCode = "aa-ET",
                            NameEnglish = "Afar (Ethiopia)",
                            NameNative = "Afar (Ethiopia)"
                        },
                        new
                        {
                            Id = 5,
                            LanguageCountryCode = "af-NA",
                            NameEnglish = "Afrikaans (Namibia)",
                            NameNative = "Afrikaans (Namibië)"
                        },
                        new
                        {
                            Id = 6,
                            LanguageCountryCode = "af-ZA",
                            NameEnglish = "Afrikaans (South Africa)",
                            NameNative = "Afrikaans (Suid-Afrika)"
                        },
                        new
                        {
                            Id = 7,
                            LanguageCountryCode = "agq-CM",
                            NameEnglish = "Aghem (Cameroon)",
                            NameNative = "Aghem (Kàmàlûŋ)"
                        },
                        new
                        {
                            Id = 8,
                            LanguageCountryCode = "ak-GH",
                            NameEnglish = "Akan (Ghana)",
                            NameNative = "Akan (Gaana)"
                        },
                        new
                        {
                            Id = 9,
                            LanguageCountryCode = "am-ET",
                            NameEnglish = "Amharic (Ethiopia)",
                            NameNative = "አማርኛ (ኢትዮጵያ)"
                        },
                        new
                        {
                            Id = 10,
                            LanguageCountryCode = "ar-001",
                            NameEnglish = "Arabic (World)",
                            NameNative = "العربية (العالم)"
                        },
                        new
                        {
                            Id = 11,
                            LanguageCountryCode = "ar-AE",
                            NameEnglish = "Arabic (United Arab Emirates)",
                            NameNative = "العربية (الإمارات العربية المتحدة)"
                        },
                        new
                        {
                            Id = 12,
                            LanguageCountryCode = "ar-BH",
                            NameEnglish = "Arabic (Bahrain)",
                            NameNative = "العربية (البحرين)"
                        },
                        new
                        {
                            Id = 13,
                            LanguageCountryCode = "ar-DJ",
                            NameEnglish = "Arabic (Djibouti)",
                            NameNative = "العربية (جيبوتي)"
                        },
                        new
                        {
                            Id = 14,
                            LanguageCountryCode = "ar-DZ",
                            NameEnglish = "Arabic (Algeria)",
                            NameNative = "العربية (الجزائر)"
                        },
                        new
                        {
                            Id = 15,
                            LanguageCountryCode = "ar-EG",
                            NameEnglish = "Arabic (Egypt)",
                            NameNative = "العربية (مصر)"
                        },
                        new
                        {
                            Id = 16,
                            LanguageCountryCode = "ar-ER",
                            NameEnglish = "Arabic (Eritrea)",
                            NameNative = "العربية (إريتريا)"
                        },
                        new
                        {
                            Id = 17,
                            LanguageCountryCode = "ar-IL",
                            NameEnglish = "Arabic (Israel)",
                            NameNative = "العربية (إسرائيل)"
                        },
                        new
                        {
                            Id = 18,
                            LanguageCountryCode = "ar-IQ",
                            NameEnglish = "Arabic (Iraq)",
                            NameNative = "العربية (العراق)"
                        },
                        new
                        {
                            Id = 19,
                            LanguageCountryCode = "ar-JO",
                            NameEnglish = "Arabic (Jordan)",
                            NameNative = "العربية (الأردن)"
                        },
                        new
                        {
                            Id = 20,
                            LanguageCountryCode = "ar-KM",
                            NameEnglish = "Arabic (Comoros)",
                            NameNative = "العربية (جزر القمر)"
                        },
                        new
                        {
                            Id = 21,
                            LanguageCountryCode = "ar-KW",
                            NameEnglish = "Arabic (Kuwait)",
                            NameNative = "العربية (الكويت)"
                        },
                        new
                        {
                            Id = 22,
                            LanguageCountryCode = "ar-LB",
                            NameEnglish = "Arabic (Lebanon)",
                            NameNative = "العربية (لبنان)"
                        },
                        new
                        {
                            Id = 23,
                            LanguageCountryCode = "ar-LY",
                            NameEnglish = "Arabic (Libya)",
                            NameNative = "العربية (ليبيا)"
                        },
                        new
                        {
                            Id = 24,
                            LanguageCountryCode = "ar-MA",
                            NameEnglish = "Arabic (Morocco)",
                            NameNative = "العربية (المغرب)"
                        },
                        new
                        {
                            Id = 25,
                            LanguageCountryCode = "ar-MR",
                            NameEnglish = "Arabic (Mauritania)",
                            NameNative = "العربية (موريتانيا)"
                        },
                        new
                        {
                            Id = 26,
                            LanguageCountryCode = "ar-OM",
                            NameEnglish = "Arabic (Oman)",
                            NameNative = "العربية (عُمان)"
                        },
                        new
                        {
                            Id = 27,
                            LanguageCountryCode = "ar-PS",
                            NameEnglish = "Arabic (Palestinian Authority)",
                            NameNative = "العربية (السلطة الفلسطينية)"
                        },
                        new
                        {
                            Id = 28,
                            LanguageCountryCode = "ar-QA",
                            NameEnglish = "Arabic (Qatar)",
                            NameNative = "العربية (قطر)"
                        },
                        new
                        {
                            Id = 29,
                            LanguageCountryCode = "ar-SA",
                            NameEnglish = "Arabic (Saudi Arabia)",
                            NameNative = "العربية (المملكة العربية السعودية)"
                        },
                        new
                        {
                            Id = 30,
                            LanguageCountryCode = "ar-SD",
                            NameEnglish = "Arabic (Sudan)",
                            NameNative = "العربية (السودان)"
                        },
                        new
                        {
                            Id = 31,
                            LanguageCountryCode = "ar-SO",
                            NameEnglish = "Arabic (Somalia)",
                            NameNative = "العربية (الصومال)"
                        },
                        new
                        {
                            Id = 32,
                            LanguageCountryCode = "ar-SS",
                            NameEnglish = "Arabic (South Sudan)",
                            NameNative = "العربية (جنوب السودان)"
                        },
                        new
                        {
                            Id = 33,
                            LanguageCountryCode = "ar-SY",
                            NameEnglish = "Arabic (Syria)",
                            NameNative = "العربية (سوريا)"
                        },
                        new
                        {
                            Id = 34,
                            LanguageCountryCode = "ar-TD",
                            NameEnglish = "Arabic (Chad)",
                            NameNative = "العربية (تشاد)"
                        },
                        new
                        {
                            Id = 35,
                            LanguageCountryCode = "ar-TN",
                            NameEnglish = "Arabic (Tunisia)",
                            NameNative = "العربية (تونس)"
                        },
                        new
                        {
                            Id = 36,
                            LanguageCountryCode = "ar-YE",
                            NameEnglish = "Arabic (Yemen)",
                            NameNative = "العربية (اليمن)"
                        },
                        new
                        {
                            Id = 37,
                            LanguageCountryCode = "arn-CL",
                            NameEnglish = "Mapuche (Chile)",
                            NameNative = "Mapuche (Chile)"
                        },
                        new
                        {
                            Id = 38,
                            LanguageCountryCode = "as-IN",
                            NameEnglish = "Assamese (India)",
                            NameNative = "অসমীয়া (ভাৰত)"
                        },
                        new
                        {
                            Id = 39,
                            LanguageCountryCode = "asa-TZ",
                            NameEnglish = "Asu (Tanzania)",
                            NameNative = "Kipare (Tadhania)"
                        },
                        new
                        {
                            Id = 40,
                            LanguageCountryCode = "ast-ES",
                            NameEnglish = "Asturian (Spain)",
                            NameNative = "asturianu (España)"
                        },
                        new
                        {
                            Id = 41,
                            LanguageCountryCode = "az-Cyrl-AZ",
                            NameEnglish = "Azerbaijani (Cyrillic, Azerbaijan)",
                            NameNative = "азәрбајҹан (Кирил, Азәрбајҹан)"
                        },
                        new
                        {
                            Id = 42,
                            LanguageCountryCode = "az-Latn-AZ",
                            NameEnglish = "Azerbaijani (Latin, Azerbaijan)",
                            NameNative = "azərbaycan (latın, Azərbaycan)"
                        },
                        new
                        {
                            Id = 43,
                            LanguageCountryCode = "ba-RU",
                            NameEnglish = "Bashkir (Russia)",
                            NameNative = "Bashkir (Russia)"
                        },
                        new
                        {
                            Id = 44,
                            LanguageCountryCode = "bas-CM",
                            NameEnglish = "Basaa (Cameroon)",
                            NameNative = "Ɓàsàa (Kàmɛ̀rûn)"
                        },
                        new
                        {
                            Id = 45,
                            LanguageCountryCode = "be-BY",
                            NameEnglish = "Belarusian (Belarus)",
                            NameNative = "беларуская (Беларусь)"
                        },
                        new
                        {
                            Id = 46,
                            LanguageCountryCode = "bem-ZM",
                            NameEnglish = "Bemba (Zambia)",
                            NameNative = "Ichibemba (Zambia)"
                        },
                        new
                        {
                            Id = 47,
                            LanguageCountryCode = "bez-TZ",
                            NameEnglish = "Bena (Tanzania)",
                            NameNative = "Hibena (Hutanzania)"
                        },
                        new
                        {
                            Id = 48,
                            LanguageCountryCode = "bg-BG",
                            NameEnglish = "Bulgarian (Bulgaria)",
                            NameNative = "български (България)"
                        },
                        new
                        {
                            Id = 49,
                            LanguageCountryCode = "bm-ML",
                            NameEnglish = "Bamanankan (Mali)",
                            NameNative = "bamanakan (Mali)"
                        },
                        new
                        {
                            Id = 50,
                            LanguageCountryCode = "bn-BD",
                            NameEnglish = "Bangla (Bangladesh)",
                            NameNative = "বাংলা (বাংলাদেশ)"
                        });
                });

            modelBuilder.Entity("galaxypremiere.Domain.Entities.Users.Roles", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "King"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = (byte)4,
                            Name = "Client"
                        },
                        new
                        {
                            Id = (byte)5,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("galaxypremiere.Domain.Entities.Users.Users", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Provider")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("galaxypremiere.Domain.Entities.Users.UsersActionsLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryKeyValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Successful")
                        .HasColumnType("bit");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("UsersActionsLog");
                });

            modelBuilder.Entity("galaxypremiere.Domain.Entities.Users.UsersInformation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<byte>("AccountType")
                        .HasColumnType("tinyint");

                    b.Property<string>("BIO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthMonth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<byte>("CurrencyId")
                        .HasColumnType("tinyint");

                    b.Property<string>("CurrentCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imdb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instagram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Linkden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Privacy")
                        .HasColumnType("tinyint");

                    b.Property<string>("Stage32")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("TimeZoneId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Twitter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("UsersId")
                        .HasColumnType("bigint");

                    b.Property<string>("Vimeo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Youtube")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UsersId");

                    b.ToTable("UsersInformation");
                });

            modelBuilder.Entity("galaxypremiere.Domain.Entities.Users.UsersInRoles", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<byte>("RolesId")
                        .HasColumnType("tinyint");

                    b.Property<long>("UsersId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RolesId");

                    b.HasIndex("UsersId");

                    b.ToTable("UsersInRoles");
                });

            modelBuilder.Entity("galaxypremiere.Domain.Entities.Users.UsersLoginLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LoginDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("UsersId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsersId");

                    b.ToTable("UsersLoginLog");
                });

            modelBuilder.Entity("galaxypremiere.Domain.Entities.Users.UsersInformation", b =>
                {
                    b.HasOne("galaxypremiere.Domain.Entities.Users.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("galaxypremiere.Domain.Entities.Users.UsersInRoles", b =>
                {
                    b.HasOne("galaxypremiere.Domain.Entities.Users.Roles", "Roles")
                        .WithMany("UsersInRoles")
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("galaxypremiere.Domain.Entities.Users.Users", "Users")
                        .WithMany("UsersInRoles")
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Roles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("galaxypremiere.Domain.Entities.Users.UsersLoginLog", b =>
                {
                    b.HasOne("galaxypremiere.Domain.Entities.Users.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("galaxypremiere.Domain.Entities.Users.Roles", b =>
                {
                    b.Navigation("UsersInRoles");
                });

            modelBuilder.Entity("galaxypremiere.Domain.Entities.Users.Users", b =>
                {
                    b.Navigation("UsersInRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
